version: '3.7'

services:
  db:
    image: postgres
    restart: always
    networks:
      - tinkoff_net
    ports:
      - "5432:5432"
    env_file:
      - .env
  server:
    build: .
    restart: always
    networks:
      - tinkoff_net
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started

networks:
  tinkoff_net:
    driver: bridge