"""empty message

Revision ID: 20eef51c4ac5
Revises: 
Create Date: 2022-12-03 14:08:30.598729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20eef51c4ac5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_table',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('Matches', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('level')
    )
    op.create_table('team_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stages', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_table')
    op.drop_table('team_table')
    op.drop_table('stage_table')
    op.drop_table('match_table')
    # ### end Alembic commands ###
