"""initial

Revision ID: ce7143825e3f
Revises: 
Create Date: 2022-12-03 15:54:55.985398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7143825e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score1', sa.Integer(), nullable=True),
    sa.Column('score2', sa.Integer(), nullable=True),
    sa.Column('team1', sa.Integer(), nullable=True),
    sa.Column('team2', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_table.id'], ),
    sa.ForeignKeyConstraint(['team1'], ['team_table.id'], ),
    sa.ForeignKeyConstraint(['team2'], ['team_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_table')
    op.drop_table('stage_table')
    op.drop_table('tournament_table')
    op.drop_table('team_table')
    # ### end Alembic commands ###
